'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

# set variable for highest value in sequence
lim = 4000000
fibo = [1, 2]


def fibonacci(limit):

    # checking that the last term in the sequence is lesser than four million
    while fibo[-1] < limit:

        # adding last two terms in the sequence for the next term
        fibo.append(fibo[-1] + fibo[-2])

        if fibo[-1] > lim:
            fibo.pop()
            break

        # recursive statement
        else:
            fibonacci(limit)

    return(fibo)


print(fibonacci(lim))

total = 0
for i in fibonacci(lim):
    if i % 2 == 0:
        total += i
print(total)
